logging:
  enabled: true
  destination: "~/.chef/sharp.log"

global:
  # chef git repo root
  git_cookbook_path: "/home/nico/sysadmin/chef/"
  # backup dir for knife sharp backup
  backupdir: "/home/nico/.chef/sharp/backups/"

# Currently only bot notifications supported
# notification operation:
# POST <url>/<channel>
# with JSON payload {"message": <message>}
notification:
  bot:
    enabled: true
    url: "http://bot.lan:18080/chef/bump/"
    channel: "foo"
    username: "Nicolas"
    # don't notify if updates are done on development chef
    skip: [dev]
    # Set to :none to skip CA cert checking
    ssl_verify_mode: :verify
    # Optional path to CA file
    ssl_ca_file: "~/.chef/my-ca.pem"

# ignore cookbooks/data bags/roles depending on chef server
# key is the name of your server (in a knife sharp server sense)
production:
  ignore_cookbooks: [ tests ]

sandboxnico:
  ignore_databags: [ staff/admin, infrastructure/mail ]
  ignore_roles: [ webserver ]

# store modifications of each deploy, to allow rollback
rollback:
  enabled: true
  destination: "/home/nico/.chef/sharp/rollbacks/"
