logging:
  enabled: true
  destination: "~/.chef/sharp.log"
global:
  git_cookbook_path: "/home/nico/sysadmin/chef/"
  backupdir: "/home/nico/.chef/sharp/backups/"
notification:
  hubot:
    enabled: true
    url: "http://your.hubot.lan:18080/hubot/chef/bump/"
    channel: "foo"
    username: "Nicolas"
    skip: [dev]
# key is the name of your server (in a knife sharp server sense)
sandboxnico:
  ignore_cookbooks: [ "tests" ]
