logging:
  enabled: true
  destination: "~/.chef/sharp.log"
global:
  git_cookbook_path: "/home/nico/sysadmin/chef/"
  backupdir: "/home/nico/.chef/sharp/backups/"
notification:
  hubot:
    enabled: true
    url: "http://your.hubot.lan:18080/hubot/chef/bump/"
    channel: "foo"
    username: "Nicolas"
